import type { Metadata } from "next";
import { Header } from "@/widgets";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PersonalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <Header/>
        <main>
            {children}
        </main>
    </>
  );
}
