import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/shared/styles/global.scss";

const interSans = Inter({
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.className}`}>{children}</body>
    </html>
  );
}
